# Generated by Django (Manual)

from django.db import migrations, models
import pgvector.django

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Ensure pgvector extension is installed
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;"
        ),
        migrations.CreateModel(
            name='FailedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('attempted_sql', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Failed Query',
                'verbose_name_plural': 'Failed Queries',
            },
        ),
        migrations.CreateModel(
            name='VerifiedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('sql_query', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Verified Query',
                'verbose_name_plural': 'Verified Queries',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SemanticAtom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('sql_snippet', models.TextField()),
                ('atom_type', models.CharField(choices=[('METRIC', 'Metric'), ('DIMENSION', 'Dimension'), ('JOIN', 'Join')], max_length=20)),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='required_by', to='django_semantic_analytics.semanticatom')),
            ],
            options={
                'verbose_name': 'Semantic Atom',
                'verbose_name_plural': 'Semantic Atoms',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
